addons:
  postgresql: 9.6
  code_climate: 5cedc31fbc3478eaad679e20c922aa26a7c2dfe0f735915b61bda5acc25d05f9
  firefox: "65.0"
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
  - nvm install node
  - node -v
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec